### PR TITLE
Service Fabric and Kubernetes comparisons

### PR DESCRIPTION
**Pull request by mikanyg**
Added section with links comparing Service Fabric and Kubernetes, usefull when needing to decide which orchestration platform to use in Azure.

### CODE REVIEW

**Comment by jjcollinge** [comment]
@mikanyg LGTM, @lawrencegripper happy for me to add a config.json to ignore Kubernetes to make Travis build pass then merge?

**Comment by mikanyg** [comment]
Curios why this was closed? Content issues, or simply the failing build? If the later I could easily have merged from master to make the build pass. Just didn't have the time yet.

**Comment by jjcollinge** [comment]
@mikanyg - Lawrence accidentially closed it, I'll validate build and merge

**Review by jjcollinge — APPROVED** [review]
LGTM

**Pull request merged**
