### PR TITLE
Add CoherentSolutions.Extensions.Hosting.ServiceFabric project and Service Fabric Handbook blog post

### PR DESCRIPTION
**Pull request by OlegKarasik**
Hello,

I have added links to project I am working on (simplifies development of reliable services) and to my blog post about Service Fabric (I update the Handbook each time so it won't get really outdated).

Hope they would find their place here :)

### CODE REVIEW

**Comment by lawrencegripper** [comment]
@OlegKarasik thanks for the contribution. The repo uses a spell checked and link checker as part of the build which has an ignore list for tech terms etc. Can you add `CoherentSolutions.Extensions.Hosting.ServiceFabric` into the `.spelling` file on a new line so it is ignored by the checker? 

https://travis-ci.com/lawrencegripper/awesome-servicefabric/builds/89926247

@MikkelHegn are you ok to have a review of this one?

**Comment by OlegKarasik** [comment]
@lawrencegripper 
> Can you add CoherentSolutions.Extensions.Hosting.ServiceFabric into the .spelling file on a new line so it is ignored by the checker?

I did this (the checks are ok now).

**Comment by OlegKarasik** [comment]
I have added one more thing to the pull request (_if this isn't appropriate I would remove it_). 

This is a docker image allows to run unit-test that use service fabric classes inside docker container. This can be useful to anyone who develop libraries for service fabric and what to do the build & test stages in docker container.

The detailed description of the purpose and how it was achieved can be found [here](https://olegkarasik.wordpress.com/2018/11/25/running-service-fabric-unit-tests-in-linux-container/).

Hope this could be useful to anyone.

**Comment by lawrencegripper** [comment]
Thanks, sorry for the delay in merging this in.

**Pull request merged**
